name: Generate pacman animation

on:
  schedule:
    - cron: "0 */12 * * *"

  workflow_dispatch:

  push:
    branches:
      - main

jobs:
  generate:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Generate pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: NicolasPiccioni
          color_background: "transparent"
          color_walls: "#c9caca"

      - name: Debug
        run: |
          pwd
          echo "----------------"
          find . -maxdepth 3 -type d
          echo "----------------"
          find . -maxdepth 3 -type f

      - name: Publish
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
